[project]
name = "SEM-FIB-Tomo mapper"
version = "1.2.0rc"
description = "SEM-FIB-Tomography Mapper is a tool designed for mapping SEM (Scanning Electron Microscope) images and SEM-FIB Tomography metadata to a uniform, schema-compliant json format."

keywords = ["SEM", "Tomography", "TIFF", "metadata", "extraction", "schema"]
license = "Apache-2.0"
repository = "https://github.com/kit-data-manager/tomo_mapper"

# This is you, the proud author of your project:
[[project.people]]
given-names = "Germaine"
family-names = "Götzelmann"
orcid = "https://orcid.org/0000-0003-3974-3728"
author = true      # is a full author of the project (i.e. appears in citations)
maintainer = true  # currently maintains the project (i.e. is a contact person)

[[project.people]]
given-names = "Gabin Thibaut"
family-names = "Oumbe Tekam"
orcid = "https://orcid.org/0000-0002-6745-3464"
author = true      # is a full author of the project (i.e. appears in citations)
maintainer = true  # currently maintains the project (i.e. is a contact person)

[[project.people]]
given-names = "Pauly"
family-names = "Christoph"
orcid = "https://orcid.org/0000-0002-6368-2067"
publication_author = true

[[project.people]]
given-names = "Rossella"
family-names = "Aversa"
orcid = "https://orcid.org/0000-0003-2534-0063"
publication_author = true

[[project.people]]
given-names = "Frank"
family-names = "Mücklich"
publication_author = true

[[project.people]]
given-names = "Michael"
family-names = "Engstler"
publication_author = true

[[project.people]]
given-names = "Jonas"
family-names = "Fell"
publication_author = true

[[project.people]]
given-names = "Sabine"
family-names = "Schlabach"
publication_author = true

[[project.people]]
given-names = "Dorothee-Vinga"
family-names = "Szabo"
orcid = "https://orcid.org/0000-0002-5139-8771"
publication_author = true


[config]
verbose = true     # show detailed information about what somesy is doing